/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Article = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'readingTime' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Text,
  'slug' : IDL.Text,
  'isBreaking' : IDL.Bool,
  'author' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'getArticleById' : IDL.Func([IDL.Nat], [Article], ['query']),
  'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getArticlesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  'getBreakingArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getFeaturedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'searchArticles' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'readingTime' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Text,
    'slug' : IDL.Text,
    'isBreaking' : IDL.Bool,
    'author' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'getArticleById' : IDL.Func([IDL.Nat], [Article], ['query']),
    'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getArticlesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'getBreakingArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getFeaturedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'searchArticles' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };